[project]
name = "hpo-3d-match"
version = "0.1.0"
description = "A Parameters Optimization Framework for Pose Estimation Algorithm Based on Point Cloud"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "optuna>=3.0",
    "numpy",
    "spatialmath-python",
    "mvtec-halcon==24111",
]

[project.scripts]
hpo-3d-match = "main:main"
