[project]
name = "hpo-3d-match"
version = "0.1.0"
description = "A Parameters Optimization Framework for Pose Estimation Algorithm Based on Point Cloud"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "cmaes>=0.10.0",
    "imageio>=2.31",
    "matplotlib",
    "mvtec-halcon==24111",
    "numpy<2",
    "optuna>=3.0",
    "scipy",
]

[tool.uv]
package = false
